spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: 112723
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: false
      hibernate.highlight_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /swagger*
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

